FROM node:22-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN npx turbo prune user-side --docker
WORKDIR /usr/src/app/out
RUN npm install

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm run db:client

RUN npx turbo run build --filter=user-side...

CMD ["npm", "run", "start-user-app"]